config/routes.rb
AngelhackBimby::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  mount RailsAdmin::Engine => '/babyadmin', :as => 'rails_admin'

  match '/about', to: 'pages#about', as: :about

  resources :pages
  resources :babies do
    resources :photos
    resources :milestones
    member do
      get :growth
    end
  end


  resources :api, only: [:show] do
    member do
      get :baby_milestones
    end
  end


  authenticated :user do
    root :to => 'babies#index'
  end

  root :to => 'pages#landing'

end

app/models/baby.rb
class Baby < ActiveRecord::Base
  attr_accessible :age, :height, :weight, :name, :gender, :user_id, :first_name, :last_name, :photos_attributes, :birthday
  
  belongs_to :user
  has_many :milestones
  has_many :photos, :dependent => :destroy
  before_save :full_name

  accepts_nested_attributes_for :photos

  def full_name
    self.name = "#{self.first_name} #{self.last_name}"
  end
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :baby_id, :milestone_type_id, :date, :photo_id, :month_achieved, :name, :photo

  belongs_to :baby
  belongs_to :milestone_type
  belongs_to :photo

  accepts_nested_attributes_for :photo

  before_save :get_month_achieved, :get_name

  def get_month_achieved
    bday = self.baby.birthday
    milestone = self.date

    difference = (milestone.year * 12 + milestone.month) - (bday.year * 12 + bday.month)

    self.month_achieved = "month_#{difference}"
  end

  def get_name
    self.name = self.milestone_type.name
  end
end

app/models/milestone_type.rb
class MilestoneType < ActiveRecord::Base
  attr_accessible :date, :name, :month, :month_num, :description

  has_many :milestone
  before_save :month_name, :lorem

  def month_name
    self.month = "month_#{self.month_num}"
  end

  def lorem
    self.description = "Congratulations!" if self.description.blank?
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :baby_id, :full_url

  belongs_to :baby 
  has_one :milestone
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :access_token, :fname, :lname, :gender
  # attr_accessible :title, :body
  
  has_many :babies
 
  # for facebook authentication
  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.new(provider:      auth.provider,
                      uid:           auth.uid,
                      email:         auth.info.email,
                      password:      Devise.friendly_token[0,20],
                      fname:    auth.extra.raw_info.first_name,
                      lname:     auth.extra.raw_info.last_name,
                      gender:        auth.extra.raw_info.gender.capitalize!,
                      access_token:  auth['credentials']['token'])
                      #username:      auth.info.nickname,
                      #avatar_path:   auth.info.image.gsub('type=square','width=200&height=200'),
                      #role:          'User')
      user.save
    end
    user
  end

  def full_name
    "#{self.fname} #{self.lname}"
  end

  def has_babies?
    self.babies.present?
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def show

  end

  def baby_milestones
    @baby = Baby.find params[:id]
    @milestones = @baby.milestones
    @milestone_types = MilestoneType.all

    render :json => {
      :baby => @baby.as_json(:include => [:milestones,:photos]),
      #:milestones_met => @milestones.as_json,
      :milestones => @milestone_types.as_json
    } 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_filter :authenticate_user!

  def index
    #get baby
    
    unless current_user.has_babies?
      redirect_to new_baby_path
    else
      @baby = current_user.babies.first
      @profile_photo = @baby.photos.first
      @photos = @baby.photos
      @babies = current_user.babies
    end

  end

  def new
    @baby = current_user.babies.new
  end

  def create
    @baby = current_user.babies.new params[:baby]

    if @baby.save
      redirect_to new_baby_photo_path(@baby)
    end
  end

  def growth
    #change to chosen baby
    
    @baby = current_user.babies.first
    @profile_photo = @baby.photos.first
    @photos = @baby.photos
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_filter :first_baby_of_user

  def index
    @baby = Baby.find params[:baby_id]
    @milestones = @baby.milestones
  end

  def new
    @baby = Baby.find params[:baby_id]
    @milestone = @baby.milestones.new 
    @photo = Photo.new
    @milestone_types = MilestoneType.all.map{|type| [type.name, type.id]}
  end

  def create
    @baby = Baby.find params[:baby_id]
    @photo = @baby.photos.create!(full_url: params[:full_url])

    @milestone = @baby.milestones.new(photo_id: @photo.id, date: DateTime.now, milestone_type_id: params[:milestone][:milestone_type_id])
    if @milestone.save
      redirect_to babies_path
    end
  end

private

  def first_baby_of_user
    @baby = current_user.babies.first
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]

      redirect_to root_path
    end
  end

  def failure
    redirect_to user_omniauth_authorize_path(:facebook)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
    if user_signed_in?
      unless current_user.has_babies?
        redirect_to new_baby_path
      end
    end
  end

  def about
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  def new
    @baby = Baby.find params[:baby_id]
    @photo = @baby.photos.new
  end

  def create
    @baby = Baby.find params[:baby_id]
    @photo = @baby.photos.new params[:photo]

    if @photo.save
      #redirect_to home_path
      redirect_to root_path
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/babies/_feed.haml
- if false
  %center
    #tiles= image_tag 'tiles2.png'
  .row
    %center
      %h3 First Talk!
    .small-9.large-10.columns
      %center
        = image_tag photo.full_url
    .small-9.large-10.columns
      %p
        %strong Carla Hampfrey said:
        My baby is now talking! I'm so happy right now. Her first word is "Mama", what a lovely girl.
      %ul.inline-list
        %li
          %a{:href => ""} Reply
        %li
          %a{:href => ""} Share
      %h6 2 Comments
      .row
        .small-3.large-2.columns
          %img{:src => "http://placehold.it/50x50&text=[img]"}/
        .small-9.large-10.columns
          %p You're baby is soooo cutee!
      .row
        .small-3.large-2.columns
          %img{:src => "http://placehold.it/50x50&text=[img]"}/
        .small-9.large-10.columns
          %p She's as beautiful as you! She has the same nose as yours! What a lovely girl.

app/views/babies/_profile.haml
.large-4.columns.pull-8#profile
  .panel
    %center
      %a{:href => "#"}
        - if @profile_photo.present?
          = image_tag @profile_photo.full_url
        - else 
          = image_tag "http://placehold.it/300x240&text=[img]"
      %h5
        =link_to  @baby.name.present? ? @baby.name : "Baby Name", babies_path
    .section-container.vertical-nav{"data-options" => "deep_linking: false; one_up: true", "data-section" => ""}
      - if @baby.milestones
        - @baby.milestones.each do |milestone|
          - if milestone
            - if milestone.milestone_type.name.include? 'Pincer'
              = image_tag 'palmar_grasp.png', style: 'max-height: 60px;'
    = link_to "See #{@baby.first_name}'s Growth", growth_baby_path(@baby)
    %br
    %br
    = link_to "Consult a Pedia", "#"

app/views/babies/growth.haml
.row
  .large-8.columns.push-4
    - if @baby.milestones.present?
      #growth{:'data-id' => @baby.id}
    - else
      #no-milestone
        Baby
        = @baby.first_name
        has no milestones yet. Why don't you add one above?
        

  = render "babies/profile"

:javascript
  $(function(){
    var tableData;
    var childData;
    var photos;

    var id = $("#growth").data("id");

    $.getJSON("/api/"+id+"/baby_milestones", function(data){
      console.log(data);
      parsedData = data;

      console.log(parsedData);

      tableData = parsedData;
      childData = parsedData.baby;
      photos = parsedData.baby.photos;

      var graph = new Graph(tableData, childData, photos);
      graph.logColumns();
    });
  });
  

app/views/babies/index.haml
.row.feeds
  .large-8.columns.push-4
    - @baby.milestones.reverse.each do |milestone|
      %center
        #tiles= image_tag 'tiles2.png'
        %h3= milestone.name
        = image_tag milestone.photo.full_url, style: 'min-width: 100%;'
        %br
        %br
        %strong= milestone.milestone_type.description
      - 4.times do
        %br

    - if false
      - photo = @babies.first.photos.first
      - if true
        %center
          #tiles= image_tag 'tiles2.png'
        .row
          %center
            %h3 He loves the teddy bear!
          .small-9.large-10.columns
            %center
              = image_tag photo.full_url
          .small-9.large-10.columns
            %p
              %strong Carla Hampfrey said:
              He liked what his father gave to him. What a sweet kid. He's so cute!
            %ul.inline-list
              %li
                %a{:href => ""} Reply
              %li
                %a{:href => ""} Share
            %h6 2 Comments
            .row
              .small-3.large-2.columns
                %img{:src => "http://placehold.it/50x50&text=[img]"}/
              .small-9.large-10.columns
                %p I loveee it! :)
            .row
              .small-3.large-2.columns
                %img{:src => "http://placehold.it/50x50&text=[img]"}/
              .small-9.large-10.columns
                %p Where did you buy that teddy bear?
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 First bath with her own!
        .small-9.large-10.columns
          %center
            = image_tag 'cute-bath-girl.jpg'
        .small-9.large-10.columns
          %p
            %strong Georgina Wheelson said:
            What a lovely little girl! She can take a bath already with her own. She's so adorable!
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p I loveee it! :)
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p She's so cutee! Haha. Georgina, you must be a good mother.
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 First Pose in the camera!
        .small-9.large-10.columns
          %center
            = image_tag 'cute-girl.jpg'
        .small-9.large-10.columns
          %p
            %strong Anne Hathawhey said:
            My baby is so cute! I'm so happy right now. She just did a pose like this when I take a shot of her. Very intelligent little girl.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p You're baby is soooo cutee!
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p She's as beautiful as you! She has the same nose as yours! What a lovely girl.
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 First baking!
        .small-9.large-10.columns
          %center
            = image_tag 'chef_baby.jpg'
        .small-9.large-10.columns
          %p
            %strong Lander Samson said:
            My son will become the most awesome chef! Haha
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p Awesome! He's so cute in that chef outfit!
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p He must be hungry now. It's your fault lander. haha
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 Eats like a Boss!
        .small-9.large-10.columns
          %center
            = image_tag 'baby-fed.jpg'
        .small-9.large-10.columns
          %p
            %strong Harold Weng said:
            He's so adorable! Very behave while eating, what a cute kid.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p Aye! I want that food, he says. haha
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p Your son looks so cute
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 Sleeping like an Angel!
        .small-9.large-10.columns
          %center
            = image_tag 'cute-sleeping.jpg'
        .small-9.large-10.columns
          %p
            %strong Martin Andragunov said:
            Look how he sleeps! What a cute kid!
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p Hahaha. He must be dreaming of a milk island.
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p He sleeps the same way like you martin! Haha
      %center
        #tiles= image_tag 'tiles2.png'
      .row
        %center
          %h3 Photography Fanboy!
        .small-9.large-10.columns
          %center
            = image_tag 'baby-photog.jpg'
        .small-9.large-10.columns
          %p
            %strong Vladimir Angelo said:
            Photography all the way! What an intelligent kid.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p Selfie mode! Haha
          .row
            .small-3.large-2.columns
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .small-9.large-10.columns
              %p He's so cute! What a bright kid.
  = render "profile"

app/views/babies/new.haml
%center
  %h3 Hi there! Can you tell me who's your baby? 
.container
  .row.main.form-sheets
    = simple_form_for @baby do |f|
      = f.input :first_name, placeholder: 'Bimby', required: true
      = f.input :last_name, placeholder: 'Bumblebee', required: true
      = f.input :age, placeholder: '1 month', required: true
      = f.input :height, placeholder: 'in cm.'
      = f.input :weight, placeholder: 'in lbs.'
      = f.input :birthday, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, order: [:day, :month, :year]
      %br
      = f.select :gender, ["Male","Female"], required: true
      .v-spacer40
      %br
      %center
        = f.button :submit, "I'm Done"

app/views/layouts/_fonts.haml
%link{:href => 'http://fonts.googleapis.com/css?family=Kreon:400, 300, 700', :rel => 'stylesheet', :type => 'text/css'}

app/views/layouts/_footer.haml
#semi-footer
  .row
    .large-12.columns
      %center
        = link_to 'Terms of Service', '#', class: 'padded'
        = link_to 'Privacy Policy', '#', class: 'padded'
        = link_to 'How it Works', '#how-it-works', class: 'padded'
        = link_to 'About', about_path , class: 'padded'
        = link_to 'FAQs', '#', class: 'padded'
        = link_to 'Contact Us', '#', :'data-reveal-id' => 'contactModal', class: 'padded'
      -# Move this to about page
        %span.shaded Proudly crafted by
        %br
          = link_to '@rbmrclo', 'http://twitter.com/rbmrclo'
          = link_to '@olegdeleon', 'http://twitter.com/olegdeleon'
          %br
          = link_to '@wetoolaguer', 'http://twitter.com/wetoolaguer'
          = link_to '@acedimasuhid', 'http://twitter.com/acedimasuhid'
 
#footer-copyright
  .row
    .large-6.columns
      .right
        = image_tag 'bimby-white.png'
    .large-6.columns
      .left
        .bimby-text= "2013"


#contactModal.reveal-modal.medium
  .centerify
    = image_tag 'bimby-small.png'

    %p We care for your babies, that's why we want to hear your concerns.

    = form_tag '#' do
      .row
        .twelve.columns
          = email_field_tag 'email', '', placeholder: 'Your E-mail'

      .row
        .twelve.columns
          = text_area_tag 'concern', '', rows: 5, placeholder: 'Your Concern'

      .row
        = link_to request.path do
          .button.success.eight.columns.offset-by-two
            Send
        -# = submit_tag 'Send',  class: 'button success eight columns offset-by-two'

  %a.close-reveal-modal= "&#215;".html_safe

app/views/layouts/_header.haml
//#header-with-logo
.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        = link_to root_path do
          = image_tag 'bimby-small.png'

  - if !user_signed_in?
    .top-bar-section
      / Right Nav Section
      %ul.right
        %li
          %p
            = link_to "#how-it-works" do
              How It Works
        %li
          %p
            = link_to about_path do
              About
        %li
          %p
            = link_to "#", :'data-reveal-id' => 'contactModal', class: 'padded'do
              Contact Us

  - if user_signed_in?
    .top-bar-section
      / Right Nav Section
      %ul.right
        %li
          %p
            - begin
              = link_to new_baby_milestone_path(@baby) do
                %i.general.foundicon-plus.minified
                Add a Milestone
            - rescue
        
        -#%li
          -#%p
            -#= link_to baby_milestones_path do
              -#Milestones Achieved
        %li
          %p
            = link_to destroy_session_path(:user), method: :delete do
              Sign Out
    

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "Bimby | Infant Growth Tracking via Photo Sharing"

  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  = csrf_meta_tag
  = render 'layouts/fonts'

%body

  .container
    .row.main
      = render 'layouts/header'
  = yield
  = render 'layouts/footer'

  = filepicker_js_include_tag 

app/views/milestones/index.haml
- @milestones.each do |milestone|
  = true

app/views/milestones/new.haml
%center
  %h3 Add a new Milestone for your baby!
.container
  .row.main.form-sheets.photos
    %center
      = simple_form_for @photo, url: baby_photos_path do |f|
        %i.general.foundicon-smiley
        %br
        = f.filepicker_field :full_url, class: 'twelve columns'
    
      = simple_form_for @milestone, url: baby_milestones_path  do |f|
        = hidden_field_tag :full_url
        = f.select :milestone_type_id, options_for_select(@milestone_types), required: true
        .v-spacer40
        %br
        %center
          = f.button :submit, "I'm Done"

:javascript
  $("input[type=submit]").click(function(e){
    e.preventDefault();
    full_url = $("#photo_full_url").val();
    $("#full_url").val(full_url);
    $("#new_milestone").submit();
  });

app/views/pages/about.haml
#about
  #founders-holder.floated-left
    = image_tag 'robbie.jpg'
    = image_tag 'ace.jpg'
    = image_tag 'weto.jpg'
    = image_tag 'oleg.jpg'


:javascript

  var windowHeight = $(window).height();

  $(document).ready(function(){
    $('#about').css('min-height', windowHeight - 150);
  });

app/views/pages/landing.haml
#main-content
  #elev-pitch-1
    %h4.text.right Let everyone know what your babies are doing and take that memories forever with you.
    %br
    %center
      = link_to image_tag('facebook.png'), user_omniauth_authorize_path(:facebook)
  
  - if false
    #sign-in-container
      %h4 Try out <span><img src="/assets/bimby-white-small.png"></img></span> today.

  - if false
    - if user_signed_in?
      %h: Hello #{current_user.full_name}
    - else
      %h1 Sign up now for your Bimby account


    = link_to "Login with fb", user_omniauth_authorize_path(:facebook) if !user_signed_in?
    = link_to "Sign Out", destroy_session_path(:user), method: :delete if user_signed_in?

#how-it-works
  .centerify
    .text You know what? It's so easy!
    .v-spacer50
    .sub-text Just like singing the A B C.
    - 5.times do
      %br
  .row
    %center
      .large-4.columns
        //%i.general.foundicon-video
        = image_tag 'baby-photog.jpg'
        %h3 Upload a Photo / Video
        %p Take an awesome picture of your baby or even a 30 secs video proving what your baby can do now.
      .large-4.columns
        //%i.general.foundicon-smiley
        = image_tag 'baby-fed.jpg'
        %h3 Choose a Milestone
        %p For every milestone that they achieve, they earn a badge that can let you track if they're growing well.
      .large-4.columns
        = image_tag 'cute_baby_sleep.jpg'
        %h3 Share It!
        %p After choosing a milestone, you're now good to share the happiness within you. Congratulations!

:javascript

  var windowHeight = $(window).height();
  var main_content = $('#main-content');

  $(document).ready(function(){
    main_content.css('min-height', windowHeight + 100);
  });

app/views/photos/new.haml
%center
  %h3 Now upload a photo and show the world how cute your baby is!
.container
  .row.main.form-sheets.photos
    = simple_form_for @photo, url: baby_photos_path, method: :post do |y|
      %center
        %i.general.foundicon-smiley
        %br
        = y.filepicker_field :full_url, class: 'twelve columns'

      %br
      %center
        = y.submit